# Generated by Django 2.2.4 on 2019-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('oily', models.CharField(max_length=2)),
                ('dry', models.CharField(max_length=2)),
                ('sensitive', models.CharField(max_length=2))
            ],
        ),
        migrations.CreateModel(
            name='item',           
   
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('imageId', models.CharField(max_length=50)),
                ('name',models.CharField(max_length=200)),
                ('price',  models.IntegerField()),
                ('gender',models.CharField(max_length=6)),
                ('category', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=100)),
                ('monthlySales', models.CharField(max_length=20)),
                ('forOily', models.IntegerField()),
                ('forDry', models.IntegerField()),
                ('forSensitive', models.IntegerField())
            ],
        ),
    ]
